[phases.setup]
nixPkgs = ["nodejs_20", "npm-9_x", "openssl"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["prisma generate", "npm run build"]

[start]
cmd = "npm run start"

[variables]
SKIP_ENV_VALIDATION = "true"

